/* tslint:disable */
/* eslint-disable */
/**
 * Image-host
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ImageGetUrlsResponse,
  ImagePutError,
} from '../models/index';
import {
    ImageGetUrlsResponseFromJSON,
    ImageGetUrlsResponseToJSON,
    ImagePutErrorFromJSON,
    ImagePutErrorToJSON,
} from '../models/index';

export interface ImagesRetrieveRequest {
    imageSize: ImagesRetrieveImageSizeEnum;
    userId: number;
}

export interface ImagesUpdateRequest {
    userId: number;
    filename: string;
    image: Blob;
}

/**
 * 
 */
export class ImagesApi extends runtime.BaseAPI {

    /**
     * Creates request options for imagesRetrieve without sending the request
     */
    async imagesRetrieveRequestOpts(requestParameters: ImagesRetrieveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['imageSize'] == null) {
            throw new runtime.RequiredError(
                'imageSize',
                'Required parameter "imageSize" was null or undefined when calling imagesRetrieve().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling imagesRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['imageSize'] != null) {
            queryParameters['image_size'] = requestParameters['imageSize'];
        }

        if (requestParameters['userId'] != null) {
            queryParameters['user_id'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/images/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns each image\'s id and absolute URL for an image owned by the user at the given size. Medium thumbnails and originals require Premium or Enterprise.
     * List image ids and URLs by user and size
     */
    async imagesRetrieveRaw(requestParameters: ImagesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImageGetUrlsResponse>> {
        const requestOptions = await this.imagesRetrieveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageGetUrlsResponseFromJSON(jsonValue));
    }

    /**
     * Returns each image\'s id and absolute URL for an image owned by the user at the given size. Medium thumbnails and originals require Premium or Enterprise.
     * List image ids and URLs by user and size
     */
    async imagesRetrieve(requestParameters: ImagesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImageGetUrlsResponse> {
        const response = await this.imagesRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for imagesUpdate without sending the request
     */
    async imagesUpdateRequestOpts(requestParameters: ImagesUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling imagesUpdate().'
            );
        }

        if (requestParameters['filename'] == null) {
            throw new runtime.RequiredError(
                'filename',
                'Required parameter "filename" was null or undefined when calling imagesUpdate().'
            );
        }

        if (requestParameters['image'] == null) {
            throw new runtime.RequiredError(
                'image',
                'Required parameter "image" was null or undefined when calling imagesUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['userId'] != null) {
            formParams.append('user_id', requestParameters['userId'] as any);
        }

        if (requestParameters['filename'] != null) {
            formParams.append('filename', requestParameters['filename'] as any);
        }

        if (requestParameters['image'] != null) {
            formParams.append('image', requestParameters['image'] as any);
        }


        let urlPath = `/api/images/`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Multipart upload that creates three `Image` objects (small thumbnail, medium thumbnail, and original)
     * Upload image
     */
    async imagesUpdateRaw(requestParameters: ImagesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.imagesUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Multipart upload that creates three `Image` objects (small thumbnail, medium thumbnail, and original)
     * Upload image
     */
    async imagesUpdate(requestParameters: ImagesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.imagesUpdateRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const ImagesRetrieveImageSizeEnum = {
    _200: '200',
    _400: '400',
    Original: 'original'
} as const;
export type ImagesRetrieveImageSizeEnum = typeof ImagesRetrieveImageSizeEnum[keyof typeof ImagesRetrieveImageSizeEnum];
