/* tslint:disable */
/* eslint-disable */
/**
 * Image-host
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ShareLinkCreate,
  ShareLinkCreateResponse,
  ShareLinkError,
} from '../models/index';
import {
    ShareLinkCreateFromJSON,
    ShareLinkCreateToJSON,
    ShareLinkCreateResponseFromJSON,
    ShareLinkCreateResponseToJSON,
    ShareLinkErrorFromJSON,
    ShareLinkErrorToJSON,
} from '../models/index';

export interface ShareLinksCreateRequest {
    shareLinkCreate: ShareLinkCreate;
}

export interface ShareLinksRetrieveRequest {
    id: number;
}

/**
 * 
 */
export class ShareLinksApi extends runtime.BaseAPI {

    /**
     * Creates request options for shareLinksCreate without sending the request
     */
    async shareLinksCreateRequestOpts(requestParameters: ShareLinksCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['shareLinkCreate'] == null) {
            throw new runtime.RequiredError(
                'shareLinkCreate',
                'Required parameter "shareLinkCreate" was null or undefined when calling shareLinksCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/share-links/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ShareLinkCreateToJSON(requestParameters['shareLinkCreate']),
        };
    }

    /**
     * Creates a `Share_Link` for the given image. Expiry is computed from now plus `expiry_seconds`.
     * Create share link
     */
    async shareLinksCreateRaw(requestParameters: ShareLinksCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShareLinkCreateResponse>> {
        const requestOptions = await this.shareLinksCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShareLinkCreateResponseFromJSON(jsonValue));
    }

    /**
     * Creates a `Share_Link` for the given image. Expiry is computed from now plus `expiry_seconds`.
     * Create share link
     */
    async shareLinksCreate(requestParameters: ShareLinksCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShareLinkCreateResponse> {
        const response = await this.shareLinksCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for shareLinksRetrieve without sending the request
     */
    async shareLinksRetrieveRequestOpts(requestParameters: ShareLinksRetrieveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling shareLinksRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/share-links/{id}/`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Redirects to the image URL referenced by this share link. The path `id` is the share link id, not the image id. Responds with 404 if the link does not exist or `expiry` is in the past.
     * Get image via share link
     */
    async shareLinksRetrieveRaw(requestParameters: ShareLinksRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.shareLinksRetrieveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Redirects to the image URL referenced by this share link. The path `id` is the share link id, not the image id. Responds with 404 if the link does not exist or `expiry` is in the past.
     * Get image via share link
     */
    async shareLinksRetrieve(requestParameters: ShareLinksRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.shareLinksRetrieveRaw(requestParameters, initOverrides);
    }

}
