/* tslint:disable */
/* eslint-disable */
/**
 * Image-host
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `Basic` - Basic
 * * `Premium` - Premium
 * * `Enterprise` - Enterprise
 * @export
 */
export const AccountTierEnum = {
    Basic: 'Basic',
    Premium: 'Premium',
    Enterprise: 'Enterprise'
} as const;
export type AccountTierEnum = typeof AccountTierEnum[keyof typeof AccountTierEnum];


export function instanceOfAccountTierEnum(value: any): boolean {
    for (const key in AccountTierEnum) {
        if (Object.prototype.hasOwnProperty.call(AccountTierEnum, key)) {
            if (AccountTierEnum[key as keyof typeof AccountTierEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AccountTierEnumFromJSON(json: any): AccountTierEnum {
    return AccountTierEnumFromJSONTyped(json, false);
}

export function AccountTierEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountTierEnum {
    return json as AccountTierEnum;
}

export function AccountTierEnumToJSON(value?: AccountTierEnum | null): any {
    return value as any;
}

export function AccountTierEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): AccountTierEnum {
    return value as AccountTierEnum;
}

