/* tslint:disable */
/* eslint-disable */
/**
 * Image-host
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * JSON body listing absolute URLs for the requested size.
 * @export
 * @interface ImageGetUrlsResponse
 */
export interface ImageGetUrlsResponse {
    /**
     * Absolute URLs of stored images for the user and size.
     * @type {Array<string>}
     * @memberof ImageGetUrlsResponse
     */
    urls: Array<string>;
}

/**
 * Check if a given object implements the ImageGetUrlsResponse interface.
 */
export function instanceOfImageGetUrlsResponse(value: object): value is ImageGetUrlsResponse {
    if (!('urls' in value) || value['urls'] === undefined) return false;
    return true;
}

export function ImageGetUrlsResponseFromJSON(json: any): ImageGetUrlsResponse {
    return ImageGetUrlsResponseFromJSONTyped(json, false);
}

export function ImageGetUrlsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageGetUrlsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'urls': json['urls'],
    };
}

export function ImageGetUrlsResponseToJSON(json: any): ImageGetUrlsResponse {
    return ImageGetUrlsResponseToJSONTyped(json, false);
}

export function ImageGetUrlsResponseToJSONTyped(value?: ImageGetUrlsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'urls': value['urls'],
    };
}

