/* tslint:disable */
/* eslint-disable */
/**
 * Image-host
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One image variant: database id and absolute URL.
 * @export
 * @interface ImageListItem
 */
export interface ImageListItem {
    /**
     * Primary key of the `Image` row for this size.
     * @type {number}
     * @memberof ImageListItem
     */
    id: number;
    /**
     * Absolute URL to the stored file for this size.
     * @type {string}
     * @memberof ImageListItem
     */
    url: string;
}

/**
 * Check if a given object implements the ImageListItem interface.
 */
export function instanceOfImageListItem(value: object): value is ImageListItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ImageListItemFromJSON(json: any): ImageListItem {
    return ImageListItemFromJSONTyped(json, false);
}

export function ImageListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageListItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
    };
}

export function ImageListItemToJSON(json: any): ImageListItem {
    return ImageListItemToJSONTyped(json, false);
}

export function ImageListItemToJSONTyped(value?: ImageListItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
    };
}

