/* tslint:disable */
/* eslint-disable */
/**
 * Image-host
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Error body when validation fails before persistence.
 * @export
 * @interface ImagePutError
 */
export interface ImagePutError {
    /**
     * Human-readable error.
     * @type {string}
     * @memberof ImagePutError
     */
    detail?: string;
}

/**
 * Check if a given object implements the ImagePutError interface.
 */
export function instanceOfImagePutError(value: object): value is ImagePutError {
    return true;
}

export function ImagePutErrorFromJSON(json: any): ImagePutError {
    return ImagePutErrorFromJSONTyped(json, false);
}

export function ImagePutErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImagePutError {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function ImagePutErrorToJSON(json: any): ImagePutError {
    return ImagePutErrorToJSONTyped(json, false);
}

export function ImagePutErrorToJSONTyped(value?: ImagePutError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detail': value['detail'],
    };
}

