/* tslint:disable */
/* eslint-disable */
/**
 * Image-host
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SizeEnum } from './SizeEnum';
import {
    SizeEnumFromJSON,
    SizeEnumFromJSONTyped,
    SizeEnumToJSON,
    SizeEnumToJSONTyped,
} from './SizeEnum';

/**
 * 
 * @export
 * @interface Image
 */
export interface Image {
    /**
     * 
     * @type {number}
     * @memberof Image
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof Image
     */
    owner: number;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    image: string;
    /**
     * 
     * @type {SizeEnum}
     * @memberof Image
     */
    size: SizeEnum;
}



/**
 * Check if a given object implements the Image interface.
 */
export function instanceOfImage(value: object): value is Image {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('owner' in value) || value['owner'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    return true;
}

export function ImageFromJSON(json: any): Image {
    return ImageFromJSONTyped(json, false);
}

export function ImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Image {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'owner': json['owner'],
        'image': json['image'],
        'size': SizeEnumFromJSON(json['size']),
    };
}

export function ImageToJSON(json: any): Image {
    return ImageToJSONTyped(json, false);
}

export function ImageToJSONTyped(value?: Omit<Image, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'owner': value['owner'],
        'image': value['image'],
        'size': SizeEnumToJSON(value['size']),
    };
}

