/* tslint:disable */
/* eslint-disable */
/**
 * Image-host
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageListItem } from './ImageListItem';
import {
    ImageListItemFromJSON,
    ImageListItemFromJSONTyped,
    ImageListItemToJSON,
    ImageListItemToJSONTyped,
} from './ImageListItem';

/**
 * JSON body listing image ids and absolute URLs for the requested size.
 * @export
 * @interface ImageGetUrlsResponse
 */
export interface ImageGetUrlsResponse {
    /**
     * 
     * @type {Array<ImageListItem>}
     * @memberof ImageGetUrlsResponse
     */
    items: Array<ImageListItem>;
}

/**
 * Check if a given object implements the ImageGetUrlsResponse interface.
 */
export function instanceOfImageGetUrlsResponse(value: object): value is ImageGetUrlsResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ImageGetUrlsResponseFromJSON(json: any): ImageGetUrlsResponse {
    return ImageGetUrlsResponseFromJSONTyped(json, false);
}

export function ImageGetUrlsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageGetUrlsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ImageListItemFromJSON)),
    };
}

export function ImageGetUrlsResponseToJSON(json: any): ImageGetUrlsResponse {
    return ImageGetUrlsResponseToJSONTyped(json, false);
}

export function ImageGetUrlsResponseToJSONTyped(value?: ImageGetUrlsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ImageListItemToJSON)),
    };
}

