/* tslint:disable */
/* eslint-disable */
/**
 * Image-host
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Error body when share link creation validation fails.
 * @export
 * @interface ShareLinkError
 */
export interface ShareLinkError {
    /**
     * Human-readable error.
     * @type {string}
     * @memberof ShareLinkError
     */
    detail?: string;
}

/**
 * Check if a given object implements the ShareLinkError interface.
 */
export function instanceOfShareLinkError(value: object): value is ShareLinkError {
    return true;
}

export function ShareLinkErrorFromJSON(json: any): ShareLinkError {
    return ShareLinkErrorFromJSONTyped(json, false);
}

export function ShareLinkErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareLinkError {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function ShareLinkErrorToJSON(json: any): ShareLinkError {
    return ShareLinkErrorToJSONTyped(json, false);
}

export function ShareLinkErrorToJSONTyped(value?: ShareLinkError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detail': value['detail'],
    };
}

