/* tslint:disable */
/* eslint-disable */
/**
 * Image-host
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShareLink
 */
export interface ShareLink {
    /**
     * 
     * @type {number}
     * @memberof ShareLink
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof ShareLink
     */
    image: number;
    /**
     * 
     * @type {Date}
     * @memberof ShareLink
     */
    expiry: Date;
}

/**
 * Check if a given object implements the ShareLink interface.
 */
export function instanceOfShareLink(value: object): value is ShareLink {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('expiry' in value) || value['expiry'] === undefined) return false;
    return true;
}

export function ShareLinkFromJSON(json: any): ShareLink {
    return ShareLinkFromJSONTyped(json, false);
}

export function ShareLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareLink {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'image': json['image'],
        'expiry': (new Date(json['expiry'])),
    };
}

export function ShareLinkToJSON(json: any): ShareLink {
    return ShareLinkToJSONTyped(json, false);
}

export function ShareLinkToJSONTyped(value?: Omit<ShareLink, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': value['image'],
        'expiry': value['expiry'].toISOString(),
    };
}

