/* tslint:disable */
/* eslint-disable */
/**
 * Image-host
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Share link row as returned after create, including the GET URL for this link.
 * @export
 * @interface ShareLinkCreateResponse
 */
export interface ShareLinkCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof ShareLinkCreateResponse
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof ShareLinkCreateResponse
     */
    image: number;
    /**
     * 
     * @type {Date}
     * @memberof ShareLinkCreateResponse
     */
    expiry: Date;
    /**
     * Absolute URL for GET /api/share-links/{id}/ (retrieve shared image).
     * @type {string}
     * @memberof ShareLinkCreateResponse
     */
    readonly url: string;
}

/**
 * Check if a given object implements the ShareLinkCreateResponse interface.
 */
export function instanceOfShareLinkCreateResponse(value: object): value is ShareLinkCreateResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('expiry' in value) || value['expiry'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ShareLinkCreateResponseFromJSON(json: any): ShareLinkCreateResponse {
    return ShareLinkCreateResponseFromJSONTyped(json, false);
}

export function ShareLinkCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareLinkCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'image': json['image'],
        'expiry': (new Date(json['expiry'])),
        'url': json['url'],
    };
}

export function ShareLinkCreateResponseToJSON(json: any): ShareLinkCreateResponse {
    return ShareLinkCreateResponseToJSONTyped(json, false);
}

export function ShareLinkCreateResponseToJSONTyped(value?: Omit<ShareLinkCreateResponse, 'id'|'url'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': value['image'],
        'expiry': value['expiry'].toISOString(),
    };
}

