/* tslint:disable */
/* eslint-disable */
/**
 * Image-host
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * JSON body to create a time-limited share link for an image.
 * @export
 * @interface ShareLinkCreate
 */
export interface ShareLinkCreate {
    /**
     * Primary key of the image to share.
     * @type {number}
     * @memberof ShareLinkCreate
     */
    image: number;
    /**
     * Seconds until the link expires (inclusive range 300–30000).
     * @type {number}
     * @memberof ShareLinkCreate
     */
    expirySeconds: number;
}

/**
 * Check if a given object implements the ShareLinkCreate interface.
 */
export function instanceOfShareLinkCreate(value: object): value is ShareLinkCreate {
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('expirySeconds' in value) || value['expirySeconds'] === undefined) return false;
    return true;
}

export function ShareLinkCreateFromJSON(json: any): ShareLinkCreate {
    return ShareLinkCreateFromJSONTyped(json, false);
}

export function ShareLinkCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareLinkCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'],
        'expirySeconds': json['expiry_seconds'],
    };
}

export function ShareLinkCreateToJSON(json: any): ShareLinkCreate {
    return ShareLinkCreateToJSONTyped(json, false);
}

export function ShareLinkCreateToJSONTyped(value?: ShareLinkCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': value['image'],
        'expiry_seconds': value['expirySeconds'],
    };
}

