/* tslint:disable */
/* eslint-disable */
/**
 * Image-host
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `200` - Small Thumbnail
 * * `400` - Medium Thumbnail
 * * `original` - Original
 * @export
 */
export const SizeEnum = {
    _200: '200',
    _400: '400',
    Original: 'original'
} as const;
export type SizeEnum = typeof SizeEnum[keyof typeof SizeEnum];


export function instanceOfSizeEnum(value: any): boolean {
    for (const key in SizeEnum) {
        if (Object.prototype.hasOwnProperty.call(SizeEnum, key)) {
            if (SizeEnum[key as keyof typeof SizeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SizeEnumFromJSON(json: any): SizeEnum {
    return SizeEnumFromJSONTyped(json, false);
}

export function SizeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): SizeEnum {
    return json as SizeEnum;
}

export function SizeEnumToJSON(value?: SizeEnum | null): any {
    return value as any;
}

export function SizeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): SizeEnum {
    return value as SizeEnum;
}

